from systems.sensor_system import SensorSystem
from systems.behavior import BehaviorSystem
from systems.movement import MovementSystem
from systems.interaction import InteractionSystem
from systems.energy_system import EnergySystem
from systems.aging import AgingSystem
from systems.reproduction import ReproductionSystem
from systems.death import DeathSystem
from systems.world_update import WorldUpdateSystem
